kind: pipeline
name: Blog

steps:
- name: install_themes
  image: docker:git
  commands:
  - git submodule update --init --recursive

- name: build_scss
  image: ruby
  commands:
  - gem install sass
  - cd themes/$THEME
  - mkdir -p resources/_gen/assets/scss/css/
  - sass assets/css/main.scss:resources/_gen/assets/scss/css/main.min.css --style compressed
  environment:
    THEME: LeaveIt

- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.55
    validate: true

- name: publish  
  image: plugins/gh-pages
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_password
    pages_directory: public/
    upstream_name: mogeko.github.io
    target_branch: master
  when:
    branch:
      - master
    event:
      exclude:
        - pull_request