kind: pipeline
name: Blog

steps:
- name: install_themes
  image: docker:git
  commands:
  - git submodule update --init --recursive

- name: build
  image: plugins/hugo
  commands:
  - apk --no-cache add git
  - wget -O- https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_extended_0.55.6_Linux-64bit.tar.gz | tar xz -C /bin
  - /bin/hugo

- name: publish  
  image: plugins/gh-pages
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_password
    pages_directory: public/
    upstream_name: mogeko.github.io
    target_branch: master
  when:
    branch:
      - master
    event:
      exclude:
        - pull_request